<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE student[
  <!ELEMENT student (firstname, lastname, id, plan)>
  <!ELEMENT firstname (#PCDATA)>
  <!ELEMENT lastname (#PCDATA)>
  <!ELEMENT id (#PCDATA)>
  <!ELEMENT plan (courses)>
  <!ELEMENT courses (course+)>
  <!ATTLIST courses year CDATA #REQUIRED>
  <!ELEMENT course (name, shortname, record?)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT shortname (#PCDATA)>
  <!ELEMENT record (marks, grade)>
  <!ELEMENT marks (#PCDATA)>
  <!ELEMENT grade (#PCDATA)>
]>

<student> 

  <firstname>Luca</firstname> 
  <lastname>Rossi</lastname> 
  <id>281283</id> 
  
  <plan> 
      <courses year="3"> 

        <course> 
          <name> Internet Programming </name> 
          <shortname>COM3113</shortname> 
          <record> 
            <marks>30</marks> 
            <grade>D</grade>           
          </record> 
        </course> 

        <course> 
          <name>Programming Techniques</name> 
          <shortname>COM3231</shortname> 
        </course> 

      </courses> 
  </plan> 

</student>